export const RECEIVE_ADDRESS = 'receive_address'
export const RECEIVE_SWIPERINF = 'receive_swiperinf'
export const RECEIVE_SHOPLIST = 'receive_shoplist'
export const SAVEUSERINF = 'saveuserinf'
export const REQSHOPINF = 'reqshopinf'
export const REQSHOPEVALUATE = 'reqShopEvaluate'
export const REQSEARCHSHOP = 'reqSearchShop'